import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Code2, ExternalLink } from "lucide-react";

import prisma from "@/lib/prisma";

export const dynamic = 'force-dynamic';

export default async function ContractsPage() {
  const dbContracts = await prisma.contract.findMany({
    include: {
      circuits: {
        include: {
          benchmarks: {
            orderBy: { createdAt: 'desc' },
            take: 1,
          }
        }
      }
    }
  });

  const CONTRACTS = dbContracts.map(c => ({
    id: c.id,
    name: c.name,
    circuits: c.circuits.map(circ => circ.name),
    language: "Compact 0.20",
    compiled: true,
    lastCommit: c.circuits[0]?.benchmarks[0]?.commitSha?.substring(0, 7) || "unknown",
    updatedAt: c.updatedAt.toLocaleDateString(),
  }));

  const CIRCUITS = dbContracts.flatMap(c => c.circuits.map(circ => {
    const latest = circ.benchmarks[0];
    return {
      circuit: circ.name,
      k: 9,
      rows: 100,
      provingMs: latest?.provingTimeMs || 0
    };
  })).filter(c => c.provingMs > 0);

  const avgProvingMs = CIRCUITS.length > 0 
    ? Math.round(CIRCUITS.reduce((s, c) => s + c.provingMs, 0) / CIRCUITS.length) 
    : 0;
  return (
    <div className="flex flex-col gap-8">
      <div>
        <h1 className="text-3xl font-bold tracking-tight">Contracts</h1>
        <p className="text-muted-foreground">
          Compact contracts compiled and tracked by CompactForge.
        </p>
      </div>

      {/* Contract summary */}
      <div className="grid gap-4 md:grid-cols-3">
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-medium">Total Contracts</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-3xl font-bold">{CONTRACTS.length}</div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-medium">Total Circuits</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-3xl font-bold">{CIRCUITS.length}</div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-medium">Avg Proving Time</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-3xl font-bold">
              {avgProvingMs} ms
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Contracts table */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Code2 className="h-5 w-5" />
            Tracked Contracts
          </CardTitle>
          <CardDescription>
            Each row represents one compiled <code>.compact</code> source file.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Name</TableHead>
                <TableHead>Language</TableHead>
                <TableHead>Circuits</TableHead>
                <TableHead>Last Commit</TableHead>
                <TableHead>Status</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {CONTRACTS.map((c) => (
                <TableRow key={c.id}>
                  <TableCell className="font-mono font-medium">{c.name}</TableCell>
                  <TableCell>{c.language}</TableCell>
                  <TableCell>
                    <div className="flex flex-wrap gap-1">
                      {c.circuits.map((circ) => (
                        <Badge key={circ} variant="secondary" className="font-mono text-xs">
                          {circ}
                        </Badge>
                      ))}
                    </div>
                  </TableCell>
                  <TableCell className="font-mono text-xs">{c.lastCommit}</TableCell>
                  <TableCell>
                    <Badge className="bg-green-500/10 text-green-500 border-green-500/20">
                      Compiled ✓
                    </Badge>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </CardContent>
      </Card>

      {/* Circuit breakdown table */}
      <Card>
        <CardHeader>
          <CardTitle>Circuit Details</CardTitle>
          <CardDescription>
            ZK circuit parameters generated by the Compact compiler.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Circuit</TableHead>
                <TableHead>k (SRS size)</TableHead>
                <TableHead>Rows</TableHead>
                <TableHead>Avg Proving Time</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {CIRCUITS.map((c) => (
                <TableRow key={c.circuit}>
                  <TableCell className="font-mono">{c.circuit}</TableCell>
                  <TableCell>{c.k}</TableCell>
                  <TableCell>{c.rows}</TableCell>
                  <TableCell>{c.provingMs} ms</TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    </div>
  );
}
